In [1]:
import numpy as np

* Student Marks Matrix
* Rows = Students
* Columns = Subjects

In [2]:
marks = np.array([ [78, 85, 90],  [45, 56, 60], [92, 88, 95], [35, 40, 38],[67, 72, 70]])

In [3]:
print("Student Marks Matrix:")
print(marks)

Student Marks Matrix:
[[78 85 90]
 [45 56 60]
 [92 88 95]
 [35 40 38]
 [67 72 70]]


In [4]:
## Shape of Matrix
print("Shape of matrix:")
marks.shape

Shape of matrix:


(5, 3)

In [5]:
# Average Marks Per Student
# axis=1 
# means row-wise

In [6]:
student_avg = np.mean(marks, axis=1)

print("Average marks of each student:")
print(student_avg)

Average marks of each student:
[84.33333333 53.66666667 91.66666667 37.66666667 69.66666667]


In [7]:
# Subject-wise Average
# axis=0 
#column-wise

In [8]:
subject_avg = np.mean(marks, axis=0)

print("Subject-wise average:")
print(subject_avg)

Subject-wise average:
[63.4 68.2 70.6]


In [9]:
# Highest Marks

highest_marks = np.max(marks)

print("Highest marks in matrix:")
print(highest_marks)

Highest marks in matrix:
95


In [10]:
# Topper
topper_index = np.argmax(student_avg)

print("Topper Student Index:")
print(topper_index)

print("Topper Average:")
print(student_avg[topper_index])

Topper Student Index:
2
Topper Average:
91.66666666666667


In [11]:
# Failed Students
# Condition: Any subject < 40

In [12]:
failed_students = np.any(marks < 40, axis=1)

In [13]:
print("Failed Students:")
print(failed_students)

Failed Students:
[False False False  True False]


In [14]:
# Print failed student indexes
print("Indexes of failed students:")

for index in range(len(failed_students)):
    if failed_students[index]:
        print(index)

Indexes of failed students:
3


**Grade System**

In [15]:
print("Student Grades:")

for i in range(len(student_avg)):

    avg = student_avg[i]

    if avg >= 90:
        grade = "A"

    elif avg >= 75:
        grade = "B"

    elif avg >= 50:
        grade = "C"

    else:
        grade = "Fail"

    print(f"Student {i} --> Average: {avg:.2f} --> Grade: {grade}")

Student Grades:
Student 0 --> Average: 84.33 --> Grade: B
Student 1 --> Average: 53.67 --> Grade: C
Student 2 --> Average: 91.67 --> Grade: A
Student 3 --> Average: 37.67 --> Grade: Fail
Student 4 --> Average: 69.67 --> Grade: C
